with-expecter: true
dir: src/mocks/
outpkg: mocks
packages:
    github.com/D8-X/twitter-referral-system/src/twitter:
        # place your package-specific config here
        config:
        interfaces:
            # select the interfaces you want mocked
            ApiRateLimiter: